# Site settings
title: naiad.io
email: cameron@naiad.io
description: automate your workflow
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://naiad.io" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://www.github.com/cjjwisniewski
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: https://www.linkedin.com/in/cameronwisniewski
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
